repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-yaml
    args: [--allow-multiple-documents]
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: 'v0.0.253'
  hooks:
    - id: ruff
      args: [ --fix, --exit-non-zero-on-fix ]
- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
  - id: black
default_language_version:
  python: python3.10
