codecov:
  require_ci_to_pass: yes

coverage:
  status:
    project:
      target: auto
      threshold: 0%
    patch:
      default:
        target: 80%  # new contributions should have a coverage at least equal to target
